[package]
name = "mcosudb"
version = "0.1.0"
authors = ["riesha <seleneia@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
serde_json = "1.0"
serde = "*"
serde_derive = "*"